# Generated by Django 5.0.1 on 2024-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_functions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
