# Generated by Django 5.0.1 on 2024-01-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_storage_owner_wheel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
