# Generated by Django 5.0.1 on 2024-02-02 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_wheel_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('wheels', models.JSONField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='accounts.team')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='products.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
