# Generated by Django 5.0.1 on 2024-02-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_acceptance_created_at_alter_acceptance_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
