# Generated by Django 5.0.1 on 2024-02-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_acceptance_wheels'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='season',
            field=models.CharField(choices=[('Зима', 'Winter'), ('Лето', 'Summer')], default='Лето', max_length=4),
        ),
    ]
