# Generated by Django 5.0.1 on 2024-02-20 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_wheel_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptance',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
