# Generated by Django 5.0.1 on 2024-02-20 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='return',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
