# Generated by Django 5.0.1 on 2024-04-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_action_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='season',
            field=models.CharField(choices=[('Зима', 'Winter'), ('Лето', 'Summer'), ('Всесезонка', 'All Season')], default='Лето', max_length=10),
        ),
    ]
